####this is a sample .yaml file for users to understand the way actual .yaml file needs to be constructed#####
# Query for the organism in NCBI databases
organism_query: "Mycobacterium[Organism]"

# Email address for NCBI notifications
email: "your@email.com"

# Organism name
organism: "Mycobacterium tuberculosis"

# Location for filtering assemblies
location: "India"

# URL to the reference genome file
reference_genome_url: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/195/955/GCF_000195955.2_ASM19595v2/GCF_000195955.2_ASM19595v2_genomic.fna.gz"

# URL to the GFF file
gff_url: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/195/955/GCF_000195955.2_ASM19595v2/GCF_000195955.2_ASM19595v2_genomic.gff.gz"

# NCBI taxonomic group
group: "bacteria"

# Organism type: PK for prokaryotes, EK for eukaryotes
organism_type: "PK"

# QUAST parameters
quast_threads: 8

# Prokka parameters
prokka_kingdom: "Bacteria"
prokka_env: "prokka_env"
prokka_params:
  cpus: 8
