name: genome_tool_env
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - biopython
  - yq
  - termcolor
  - tqdm
  - prokka
  - quast
  - ncbi-genome-download
