name: assembly_tool_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.8
  - pandas
  - pyyaml
  - biopython
  - termcolor
  - tqdm
  - ncbi-genome-download
  - quast
  - prokka
  - wget
